#!/bin/sh
# $Id: password,v 1.7 2010/01/13 10:20:03 tom Exp $

. ./setup-vars

. ./setup-tempfile

$DIALOG --title "INPUT BOX" --clear "$@" \
        --passwordbox "Try entering your name below:" 16 51 2> $tempfile

retval=$?

. ./report-tempfile