- name:
  shell: echo "Подготовка Выполнено Обновление_ОС Выполнено Установка_пакетов Выполнено Настройка_контроллера Выполняется" >> /tmp/b.txt

- name: Deploy first controller
  shell: aldpro-server-install -d "{{ FQDN.split(".")[1:]|join(".") }}" -n "{{ FQDN.split(".")[0] }}" -p "{{ admin_password }}" --ip "{{ ip_address }}" --no-reboot

- name:
  shell: echo 90 > /tmp/a.txt
