- name: Add FQDN hostname to Firefox homepage instead of short hostname
  shell:
    cmd: 'sed -i "s/https:\/\/.*\$/https:\/\/{{ FQDN }}\/\",/g" /usr/lib/firefox/distribution/policies.json'

- name:
  shell: echo -e "XXX\n100"
  register: out

- name:
  debug:
    var: out.stdout_lines