- name: Deploy hosts configuration
  template:
    src: hosts.j2
    dest: "/etc/hosts"

- name:
  shell: |
    echo -e "XXX\n50\n[Выполняется] : Подготовка\n[Ожидает] : Обновление_ОС\n[Ожидает] : Установка_пакетов\n[Ожидает] : Настройка_контроллера\nXXX" >> /tmp/log.txt