- name:
  shell: echo -e "XXX\n60\n[Выполнено] : Подготовка\n[Выполнено] : Обновление_ОС\n[Выполняется] : Установка_пакетов\n[Ожидает] : Настройка_контроллера\nXXX" >> /tmp/log.txt

- name: Install packet aldpro-mp
  apt:
    name: aldpro-mp
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive 

- name:
  shell: echo -e "XXX\n70\n[Выполнено] : Подготовка\n[Выполнено] : Обновление_ОС\n[Выполняется] : Установка_пакетов\n[Ожидает] : Настройка_контроллера\nXXX" >> /tmp/log.txt