- name:
  shell: echo "Подготовка Выполнено Обновление_ОС Выполнено Установка_пакетов Выполняется Настройка_контроллера Ожидает" >> /tmp/b.txt

- name: Install packet aldpro-mp
  apt:
    name: aldpro-mp
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive 

- name:
  shell: echo 70 > /tmp/a.txt