- name: Deploy network configuration
  template:
    src: interfaces.j2
    dest: "/etc/network/interfaces"
  notify: "apply network configuration"

- name: Flush handlers
  meta: flush_handlers

- name:
  shell: echo -e "XXX\n20"
  register: out

- name:
  debug:
    var: out.stdout_lines
