- name:
  shell: echo "Подготовка Выполняется Обновление_ОС Ожидает Установка_пакетов Ожидает Настройка_контроллера Ожидает" >> /tmp/b.txt

- name: Disable NetworkManager
  service:
    name: NetworkManager
    enabled: false
    state: stopped

- name: Mask NetworkManager
  shell: systemctl mask NetworkManager.service

- name:
  shell: echo 10 > /tmp/a.txt