- name: Disable NetworkManager
  service:
    name: NetworkManager
    enabled: false
    state: stopped

- name: Mask NetworkManager
  shell: systemctl mask NetworkManager.service

- name:
  shell: echo -e "XXX\n10"
  register: out

- name:
  debug:
    var: out.stdout_lines