- name:
  shell: systemctl set-default graphical.target

- name:
  file:
    path: /etc/systemd/system/getty@tty1.service
    state: absent

- name:
  replace:
    path: /home/localadmin/.profile
    regexp: 'cd ALDPro-deploy; bash form'
    replace: ''

- name:
  copy:
    src: /usr/login
    dest: /etc/pam.d/login
    owner: root
    group: root
    mode: '0644'

- name: change password
  user:
    name: localadmin
    state: present
    password: "{{ admin_password | password_hash('sha512') }}"

- name:
  shell: |
    echo -e "XXX\n100\n[Выполнено] : Подготовка\n[Выполнено] : Обновление_ОС\n[Выполнено] : Установка_пакетов\n[Выполнено] : Настройка_контроллера\nXXX" >> /tmp/log.txt