- name:
  shell: echo -e "XXX\n50\n[Выполнено] : Подготовка\n[Выполняется] : Обновление_ОС\n[Ожидает] : Установка_пакетов\n[Ожидает] : Настройка_контроллера\nXXX" >> /tmp/log.txt

- name: Update repositories cache and upgrade packets
  apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confnew'

- name:
  shell: echo -e "XXX\n60\n[Выполнено] : Подготовка\n[Выполнено] : Обновление_ОС\n[Ожидает] : Установка_пакетов\n[Ожидает] : Настройка_контроллера\nXXX" >> /tmp/log.txt