- name:
  shell: echo "Подготовка Выполнено Обновление_ОС Выполняется Установка_пакетов Ожидает Настройка_контроллера Ожидает" > /tmp/b.txt

- name: Update repositories cache and upgrade packets
  apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confnew'

- name:
  shell: echo 60 > /tmp/a.txt